apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "exim4.fullname" . }}-files
  labels:
    app: {{ template "exim4.name" . }}
    chart: {{ template "exim4.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  localmacros: | {{ .Values.configFiles.localmacros | nindent 4 }}
