apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "exim4.fullname" . }}
  labels:
    app: {{ template "exim4.name" . }}
    chart: {{ template "exim4.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "exim4.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "exim4.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.gmail }}
            - name: GMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gmail.user.secretName }}
                  key: {{ .Values.gmail.user.secretKey }}
            - name: GMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gmail.password.secretname }}
                  key: {{ .Values.gmail.password.secretKey }}
            {{- end }}
          ports:
            - containerPort: 25
          resources: {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-files
              mountPath: /etc/exim4/exim4.conf.localmacros
              subPath: localmacros
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-files
          configMap:
            name: {{ template "exim4.fullname" . }}-files
