apiVersion: v1
kind: Service
metadata:
  name: {{ template "exim4.fullname" . }}
  labels:
    app: {{ template "exim4.name" . }}
    chart: {{ template "exim4.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 25
      protocol: TCP
      name: smtp
  selector:
    app: {{ template "exim4.name" . }}
    release: {{ .Release.Name }}
