# Default values for exim4.

replicaCount: 1

image:
  repository: tianon/exim4
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 1025

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

configFiles:
  # See: https://wiki.debian.org/Exim#Single_Exim4_configuration_file
  localmacros: |
    # Base configuration options.
    disable_ipv6 = true

# This section allows to enable Gmail relay.
#
# Note that creating a secret with credentials is not the responsibility
# of this Helm Chart, due to security reasons.
gmail:
  user:
    secretName: exim4-gmail
    secretKey: gmail-user
  password:
    secretname: exim4-gmail
    secretKey: gmail-password
